
#Block configuration settings
[block]

	#Rime configuration settings
	[block.rime]
		#Whether or not rime can freeze water.
		canFreezeWater = true
		#Whether or not rime can freeze entities.
		canFreezeLava = true

