
[General]
	#When enabled, only shows the areaname in the HUD. When disabled, the prefixes and suffices will also be used.
	_HUDOnlyAreaName = false
	#The green RGB value for the HUD message.
	#Range: 0 ~ 255
	_HUD_RGB_G = 200
	#The blue RGB value for the HUD message.
	#Range: 0 ~ 255
	_HUD_RGB_B = 50
	#When enabled, sends the player the area notifications in chat.
	__sendChatMessages = false
	#The suffix of the message whenever a player leaves a named biome area.
	biomeLeaveSuffix = "."
	#The vertical offset (y coord) for the HUD message. This determines how far down the message should be on the screen. Can be changed to prevent GUIs from overlapping.
	#Range: 0 ~ 3000
	_HUDMessageHeightOffset = 10
	#The prefix of the message whenever a player enters an area.
	joinPrefix = "Entering "
	#The suffix of the message whenever a player enters an area.
	joinSuffixx = "."
	#When enabled, sends the player the area notifications in the HUD on screen.
	__showHUDMessages = true
	#The suffix of the message whenever a player enters a named biome area.
	biomeJoinSuffix = "."
	#The suffix of the message whenever a player leaves an area.
	leaveSuffix = "."
	#The prefix of the message whenever a player leaves a named biome area.
	biomeLeavePrefix = "Leaving the biome named "
	#The prefix of the message whenever a player enters a named biome area.
	biomeJoinPrefix = "Entering the biome named "
	#The red RGB value for the HUD message.
	#Range: 0 ~ 255
	_HUD_RGB_R = 100
	#The prefix of the message whenever a player leaves an area.
	leavePrefix = "Leaving "
	#The delay in ms after which the HUD message should fade out.
	#Range: 100 ~ 360000
	_HUDMessageFadeDelayMs = 3500

