
[General]
	#Use the list of pre-defined female names when naming villagers.
	_useFemaleNames = true
	#Use the list of pre-defined male names when naming villagers.
	_useMaleNames = true
	#Use the custom name list, editable in ./mods/villagernames/customnames.txt, seperated by a comma.
	_useCustomNames = false

