
#Miscellaneous
[miscellaneous]
	#Disables thunder storms, fixing glitched lighting from thunder and other side-effects
	enableStormTweak = false
	#Prints your death point in chat
	enableDeathPoint = false
	#Show food hunger & saturation on item hover
	#Allowed Values: NEVER, WITH_SHIFT, ALWAYS
	foodTooltipSetting = "NEVER"
	#Show a welcome message in chat when joining a world for the first time
	enableGuideNotifier = false
	#Show tool durability on item hover
	#Allowed Values: NEVER, WITH_SHIFT, ALWAYS
	durabilityTooltipSetting = "WITH_SHIFT"

#Block Tweaks
["block tweaks"]
	#A list of blocks to ignore, of form <modid:block>
	cropTweaksBlacklist = []
	#Allows for r-clicking to harvest most any (including mod) crops
	cropTweaksEnabled = false
	#Allows more plants to be bonemealed
	enableBonemealTweak = true
	#Fixes some tools NOT being effective on certain materials
	enableToolEffTweaks = true
	#Allows for uneaten cake to drop on break
	enableCakeDrop = true

#Player Tweaks
["player tweaks"]
	#Adds parity to Player arm swings (inspired by snapshot 19W42A)
	enableArmSwingParity = true

#Enchantments
[enchantments]
	#Number of levels Imperishable costs to create in an anvil
	#Range: 1 ~ 40
	imperishableCost = 30
	#Should the lumbering enchantments also prune the leaves of a tree?
	lumberingCutsLeaves = true
	#Enable the Imperishable enchantment for any breakable item
	enableImperishable = true
	#Feather Falling IV or above directs 100% of fall damage to boots
	enableFeatherFallTweak = true
	#Number of levels Lumbering costs to create in an anvil
	#Range: 1 ~ 40
	lumberingCost = 16
	#Enable the Lumbering enchantment for Axes
	enableLumbering = true

#Mob Tweaks
["mob tweaks"]
	#Enable custom nametags on challenger mobs
	challengerMobsNames = true
	#A list of dimensions (of form <modid:type>) to ignore when prevent surface mob spawns.
	peacefulSurfaceDimBlacklist = ["minecraft:the_nether", "minecraft:the_end"]
	#Allows chicken feathers to be plucked w/ shears
	enableFeatherPlucking = true
	#The lowest Y-level which mobs will be prevented from spawning
	#Range: 1 ~ 255
	peacefulSurfaceMinY = 60
	#Enabling this allows tamed pets to pick up weapons (which do actually work but don't render)
	enablePetWeaponry = false
	#Randomly spawns more difficult (but more lootworthy) enemies.
	#Applies to ALL enemies but those in this blacklist.
	challengerMobsEnabled = true
	#The class name (or part of it) of any entities that should not be turned to challenger mobs
	challengerMobsBlacklist = []
	#The frequency (out of 100 - higher means more frequent) of a mob being turned into a Challenger
	#Range: 1 ~ 100
	challengerMobsFrequency = 15
	#Enable colored particles for challenger mobs (dependent on particle setting as well)
	enableChallengerMobParticles = true
	#Prevents mobs from spawning above sea level unless it's a new moon
	peacefulSurfaceEnabled = false
	#Chance (out of 100) that a passive mob can spawn as a baby.
	#0 to disable feature.
	#Range: 0 ~ 100
	naturalBabiesChance = 30
	#A string list of form <modid:item> of possible loot items a Challenger Mob could drop
	challengerMobsLoot = ["minecraft:gold_ingot", "minecraft:gold_nugget*15", "minecraft:diamond", "minecraft:emerald", "minecraft:ghast_tear", "minecraft:ender_pearl", "minecraft:emerald", "minecraft:experience_bottle"]
	#Allows you to R-Click your tamed pets with horse armor
	enablePetArmory = false

#Item Tweaks
["item tweaks"]
	#Allows egg items in the world to hatch instead of despawn
	eggHatchingEnabled = true
	#The chance (out of 100 - higher means more frequent) that the egg will turn into a chick
	#**DO NOT SET THIS TOO HIGH OR ELSE CHICKENS MAY INFINITELY LAG YOUR WORLD**
	#Range: 1 ~ 100
	eggHatchingChance = 1
	#Convert Concrete Powder to Concrete when the item is thrown into water
	enableConreteTweaks = true
	#Allow for modifications to item despawn timers
	enableDespawnTimeAdjustments = false
	#Adjust Item Despawn Time (in ticks: 20 ticks in a second - default despawn delay is 6000 ticks)
	#-1 prevents items from despawning at all.
	#If other "do x on despawn" configs are enabled, then those items **will still despawn**
	#Range: > -1
	despawnTimeAdjustments = 6000
	#Instead of de-spawning, saplings will attempt to plant themselves
	enableSaplingPlanting = true

