
#
#Configure which Modules should be accessible in recipes and creative menus.
[modules]
	enableSchematics = true
	enableCuriosities = true
	enablePalettes = true
	enableLogistics = true

#
#The Backbone of Create
[infrastructure]
	#
	#[in Ticks]
	#The amount of time a server waits before sending out tickrate synchronization packets.
	#These packets help animations to be more accurate when tps is below 20.
	#Range: > 5
	tickrateSyncTimer = 20

#
#The Contraptions Module
[kinetics]
	#
	#Disable the Stress mechanic altogether.
	disableStress = false
	#
	#Maximum length in blocks of mechanical belts.
	#Range: > 5
	maxBeltLength = 20
	#
	#Damage dealt by active Crushing Wheels.
	#Range: > 0
	crushingDamage = 4
	#
	#[in Revolutions per Minute]
	#Maximum allowed speed of a configurable motor.
	#Range: > 64
	maxMotorSpeed = 256
	#
	#[in Revolutions per Minute]
	#Rotation speed gained by a water wheel for each side with running water. (halved if not against blades)
	#Range: > 1
	waterWheelSpeed = 5
	#
	#[in Revolutions per Minute]
	#Base rotation speed for the furnace engine generator
	#Range: > 1
	furnaceEngineSpeed = 16
	#
	#[in Revolutions per Minute]
	#Maximum allowed rotation speed for any Kinetic Tile.
	#Range: > 64
	maxRotationSpeed = 256
	#
	#Select what mobs should ignore Deployers when attacked by them.
	#Allowed Values: ALL, CREEPERS, NONE
	ignoreDeployerAttacks = "CREEPERS"
	#
	#Game ticks between Kinetic Blocks checking whether their source is still valid.
	#Range: > 5
	kineticValidationFrequency = 60

	#
	#Encased Fan
	[kinetics.encasedFan]
		#
		#Maximum distance in blocks Fans can push entities.
		#Range: > 5
		fanPushDistance = 20
		#
		#Maximum distance in blocks from where Fans can pull entities.
		#Range: > 5
		fanPullDistance = 20
		#
		#Game ticks between Fans checking for anything blocking their air flow.
		#Range: > 10
		fanBlockCheckRate = 30
		#
		#[in Revolutions per Minute]
		#Rotation speed at which the maximum stats of fans are reached.
		#Range: > 64
		fanRotationArgmax = 256
		#
		#[in Revolutions per Minute]
		#Rotation speed generated by a vertical fan above fire.
		#Range: > 0
		generatingFanSpeed = 16
		#
		#Game ticks required for a Fan-based processing recipe to take effect.
		#Range: > 0
		inWorldProcessingTime = 150

	#
	#Moving Contraptions
	[kinetics.contraptions]
		#
		#Maximum amount of blocks in a structure movable by Pistons, Bearings or other means.
		#Range: > 1
		maxBlocksMoved = 2048
		#
		#Maximum value of a chassis attachment range.
		#Range: > 1
		maxChassisRange = 16
		#
		#Maximum amount of extension poles behind a Mechanical Piston.
		#Range: > 1
		maxPistonPoles = 64
		#
		#Max length of rope available off a Rope Pulley.
		#Range: > 1
		maxRopeLength = 128

	#
	#Configure speed/capacity levels for requirements and indicators.
	[kinetics.stats]
		#
		#[in Revolutions per Minute]
		#Minimum speed of rotation to be considered 'medium'
		#Range: 0.0 ~ 4096.0
		mediumSpeed = 30.0
		#
		#[in Revolutions per Minute]
		#Minimum speed of rotation to be considered 'fast'
		#Range: 0.0 ~ 65535.0
		fastSpeed = 100.0
		#
		#[in Stress Units]
		#Minimum stress impact to be considered 'medium'
		#Range: 0.0 ~ 4096.0
		mediumStressImpact = 4.0
		#
		#[in Stress Units]
		#Minimum stress impact to be considered 'high'
		#Range: 0.0 ~ 65535.0
		highStressImpact = 8.0
		#
		#[in Stress Units]
		#Minimum added Capacity by sources to be considered 'medium'
		#Range: 0.0 ~ 4096.0
		mediumCapacity = 128.0
		#
		#[in Stress Units]
		#Minimum added Capacity by sources to be considered 'high'
		#Range: 0.0 ~ 65535.0
		highCapacity = 512.0

	[kinetics.stressValues]

		#
		#Fine tune the kinetic stats of individual components
		[kinetics.stressValues.v1]

			#
			#[in Stress Units]
			#Configure the individual stress impact of mechanical blocks. Note that this cost is doubled for every speed increase it receives.
			[kinetics.stressValues.v1.impact]
				shaft = 0.0
				cogwheel = 0.0
				large_cogwheel = 0.0
				encased_shaft = 0.0
				gearbox = 0.0
				clutch = 0.0
				gearshift = 0.0
				encased_belt = 0.0
				adjustable_pulley = 0.0
				belt = 1.0
				creative_motor = 0.0
				water_wheel = 0.0
				encased_fan = 1.0
				turntable = 2.0
				hand_crank = 0.0
				cuckoo_clock = 1.0
				mysterious_cuckoo_clock = 0.0
				millstone = 4.0
				crushing_wheel = 8.0
				mechanical_press = 8.0
				mechanical_mixer = 4.0
				speed_gauge = 0.0
				stress_gauge = 0.0
				mechanical_piston = 2.0
				sticky_mechanical_piston = 2.0
				mechanical_bearing = 2.0
				clockwork_bearing = 2.0
				rope_pulley = 2.0
				drill = 4.0
				saw = 4.0
				deployer = 4.0
				mechanical_crafter = 2.0
				sequenced_gearshift = 0.0
				flywheel = 0.0
				rotation_speed_controller = 0.0

			#
			#[in Stress Units]
			#Configure how much stress a source can accommodate for.
			[kinetics.stressValues.v1.capacity]
				creative_motor = 2048.0
				water_wheel = 8.0
				encased_fan = 32.0
				hand_crank = 32.0
				mechanical_bearing = 512.0
				furnace_engine = 1024.0

	#
	#The Logistics Module
	[kinetics.logistics]
		#
		#The amount of game ticks an Extractor waits after pulling an item successfully.
		#Range: > 10
		extractorDelay = 20
		#
		#The amount of game ticks an Extractor waits before checking again if the attached inventory contains items to extract.
		#Range: > 10
		extractorInventoryScanDelay = 40
		#
		#The amount of items an extractor pulls at a time without an applied filter.
		#Range: 1 ~ 64
		extractorAmount = 16
		#
		#Maximum possible range in blocks of redstone link connections.
		#Range: > 1
		linkRange = 128

	#
	#The Schematics Module
	[kinetics.schematics]
		#
		#[in KiloBytes]
		#The maximum allowed file size of uploaded Schematics.
		#Range: > 16
		maxSchematics = 256
		#
		#[in Bytes]
		#The maximum packet size uploaded Schematics are split into.
		#Range: 256 ~ 32767
		maxSchematicPacketSize = 1024
		#
		#Amount of game ticks without new packets arriving until an active schematic upload process is discarded.
		#Range: > 100
		schematicIdleTimeout = 600

		#
		#Schematicannon
		[kinetics.schematics.schematicannon]
			#
			#Amount of game ticks between shots of the cannon. Higher => Slower
			#Range: > 1
			schematicannonDelay = 10
			#
			#Amount of block positions per tick scanned by a running cannon. Higher => Faster
			#Range: > 1
			schematicannonSkips = 10
			#
			#% of Schematicannon's Fuel filled by 1 Gunpowder.
			#Range: 0.0 ~ 100.0
			schematicannonGunpowderWorth = 20.0
			#
			#% of Schematicannon's Fuel used for each fired block.
			#Range: 0.0 ~ 100.0
			schematicannonFuelUsage = 0.05000000074505806

	#
	#Everything that spins
	[kinetics.curiosities]
		#
		#The Maximum Distance to an active mirror for the symmetry wand to trigger.
		#Range: > 10
		maxSymmetryWandRange = 50
		#
		#The maximum amount of operations, a blockzapper can remember for undoing. (0 to disable undo)
		#Range: > 0
		zapperUndoLogLength = 10
		#
		#The amount of Light sources destroyed before Chromatic Compound turns into Refined Radiance.
		#Range: > 1
		lightSourceCountForRefinedRadiance = 10
		#
		#Allow Glass Panes to be put inside Blocks like Stairs, Slabs, Fences etc.
		allowGlassPanesInPartialBlocks = true
		#
		#Allow the standard Refined Radiance recipes.
		enableRefinedRadianceRecipe = true
		#
		#Allow the standard Shadow Steel recipe.
		enableShadowSteelRecipe = true
		#
		#Enable the tool repairing mechanic involving sand paper.
		enableSandPaperToolPolishing = true
		#
		#% of random Ticks causing a Cocoa log to grow.
		#Range: 0.0 ~ 100.0
		cocoaLogGrowthSpeed = 20.0

	#
	#You can try inhibiting related game mechanics for troubleshooting repeated crashes.
	[kinetics.damageControl]
		#
		#In case Crushing Wheels crushed your server.
		freezeCrushing = false
		#
		#In case Extractors pulled the plug.
		freezeExtractors = false
		#
		#In case Encased Fans tried smelting your hardware.
		freezeInWorldProcessing = false
		#
		#Pauses rotation logic altogether - Use if crash mentions RotationPropagators.
		freezeRotationPropagator = false
		#
		#In case Mechanical Bearings turned against you.
		freezeBearingConstructs = false
		#
		#In case Mechanical Pistons pushed it too far.
		freezePistonConstructs = false

